version: "3"
services:
  ehbot:
    image: ghcr.io/aiza2a/ehbot:v1.1.0
    container_name: ehbot
    restart: always
    network_mode: "host"
    environment:
      CONFIG_FILE: "/config.yaml"
      TZ: Asia/Shanghai
    volumes:
      - "./config.yaml:/config.yaml:ro"
    logging:
      driver: journald
